vs:
  width: 800
  height: 600
  fullscreen: false
  rows: 4
  cols: 4
  total_trials: 2
  fixation_time: 600 # (ms)
  post_trial_pause: 2000 # (ms)
  response_timeout: 3 # (s)
  angles: [0, 90, 180, 270]
  output_file: 'vs_results.csv'
  background_color: [120, 120, 120] # gray
  fixation_color: [0, 0, 0] # black

surveys:
  sart_save_path: 'sart_results.csv'
  nasa_tlx_save_path: 'nasa_tlx_results.csv'
  fullscreen: true

mot:
  width: 800
  height: 600
  fullscreen: false
  num_objects: 15
  num_targets: 3
  radius: 25
  total_trials: 2
  speed: 4.0
  fixation_time: 1000 # (ms)
  target_display_time: 2000 # (ms)
  trial_time: 6.0 # (s)
  post_trial_pause: 2000 # (ms)
  output_file: 'mot_results.csv'
  background_color: [120, 120, 120] # gray
  fixation_color: [0, 0, 0] # black
