colors:
  white: [255, 255, 255]
  black: [0, 0, 0]
  gray: [120, 120, 120]

vs:
  width: 800
  height: 600
  num_items: 12
  iti_time: 500
  total_trials: 5
  fixation_time: 600
  isi_time: 600
  response_timeout: 2.0
  stim_size: 40
  angles: [0, 90, 180, 270]
  defective_types: ['left_short', 'right_short']
  save_path: 'vs_results.csv'

mot:
  width: 800
  height: 600
  num_objects: 10
  num_targets: 3
  radius: 20
  n_trials: 3
  speed: 2.0
  speed_step: 0.25
  highlight_time: 2.0
  trial_time: 6.0
  output_file: 'mot_results.csv'
  random_seed: 42
