colors:
  white: [255, 255, 255]
  black: [0, 0, 0]
  gray:  [120, 120, 120]

window:
  width: 800
  height: 600

timing:
  fixation_time: 600
  isi_time: 600
  response_timeout: 2.0
  iti_time: 300



stimuli:
  stim_size: 40

  angles:
    - 0
    - 90
    - 180
    - 270

  defective_types:
    - left_short
    - right_short

vs:
  num_items: 12        # fixed difficulty
  iti_time: 500        # inter-trial interval
  total_trials: 5      # run task exactly 5 times

files:
  results: "vs_results.csv"
